config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'
  get 'comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
devise_for :users, controllers: 
      {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

devise_for :admins, controllers: 
      {
        sessions: 'admins/sessions'
      }
      
      
  root 'homes#top'
    get 'top' => 'homes#top'
    get 'sekais/mysekai' => 'sekais#mysekai'
    get '/sekais/myfav' => 'sekais#favindex'
    post 'sekais' => 'sekais#create'
    patch 'sekais/:id' => 'sekais#update'
  
  resources :sekais do
     resource :favorites, only: [:create, :destroy]
     resources :comments, only: [:create, :destroy]
     resources :tags

  end
  
  resources :users  
    get 'favorite_rank' => 'sekais#favorite_rank'
    
    
  resources :tags do
    get 'sekais', to: 'sekais#search'
  end
  
    get '/search', to: 'search#search'

  
#   resources :users do
#         resources :sekais

#   end#   resources :sekais
  
#  get 'user/sekais/new', to: 'user/sekais#new'

end

app/models/sekai.rb
class Sekai < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  
  attachment :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end      
	
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
  
    old_tags.each do |old|
      self.tag_maps.delete Tag.find_by(tag_name: old)
    end
  
    new_tags.each do |new|
      new_tag_map = Tag.find_or_create_by(tag_name: new)
      self.tag_maps << new_tag_map
    end
  end
  
  
  def self.search_for(content)
    Sekai.where('name LIKE ?', '%'+content+'%')
  end
  
end

app/controllers/sekais_controller.rb
class SekaisController < ApplicationController
    
    def new
    @sekai = current_user.sekais.new #(favorite_params)
    end
    
  def create
    # # １. データを新規登録するためのインスタンス作成
    # sekai = Sekai.new(sekai_params)
    # # ２. データをデータベースに保存するためのsaveメソッド実行
    # sekai.save
    # # ３. トップ画面へリダイレクト
    # redirect_to '/sekais'
    
    @sekai = current_user.sekais.new(sekai_params)
    tag_list = params[:sekai][:tag_name].split(' ')
    if @sekai.save
      tags = []
      tag_list.each do |tag_name|
        tags << Tag.find_or_create_by(tag_name: tag_name)
      end
      @sekai.tags = tags
      # @sekai.save_tag(tag_list)
    redirect_to '/sekais'
    else
    render :new
    end
  end
  
  def index
      @user = current_user
      @sekais =  current_user.sekais
      @sekais = Sekai.find(Favorite.group(:sekai_id).order('count(user_id) desc').limit(100).pluck(:sekai_id))
      if @sekais.length < 100
      @sekais_nil = Sekai.includes(:favorites).where( :favorites => { :id => nil } ).limit(100 - @sekais.length)
      else
      @sekais_nil = []
      end
      @sekais.push(@sekais_nil)
      @sekais.flatten!
      #上のコードを実装したい。したのは仮
      #@sekais = Sekai.all
     # sekais = Sekai.includes(:favorites).references(:favorites).group('sekai_id').order('user_id desc').each {|s| puts s.name}
      @tag_list = Tag.all
      # @sekai = current_user.sekais.new
      
  end
  
  def show
      @user = current_user
    @sekai = Sekai.find(params[:id])
    @sekai_tags = @sekai.tags  
    @comment = Comment.new

  end
  
  def edit
    @sekai = Sekai.find(params[:id])
    @tag_list = @sekai.tags  

  end
  
  def update
    @sekai = Sekai.find(params[:id])
    tag_list = params[:sekai][:tag_name].split(' ')
    if @sekai.update(sekai_params)
      tags = []
      tag_list.each do |tag_name|
        tags << Tag.find_or_create_by(tag_name: tag_name)
      end    
      @sekai.tags = tags
    end
    redirect_to sekais_path(@sekai.id)
  end
  
  def destroy
    sekai = Sekai.find(params[:id])  
    sekai.destroy  
    redirect_to sekais_path  
  end
  
  # def favorite_rank
  #   @sekai = current_user.sekais.new(favorite_params)
  #   tag_list = params[:sekai][:tag_name].split(nil)  
  #   if @sekai.save                                         
  #     @sekai.save_tag(tag_list)                         
  #   redirect_to '/sekais'
  #   else
  #   redirect_to '/sekais'
  #   end
  # end
  
  def search
      @user = current_user
    @tag_list = Tag.all  #こっちの投稿一覧表示ページでも全てのタグを表示するために、タグを全取得
    @tag = Tag.find(params[:tag_id])  #クリックしたタグを取得
    @sekais = @tag.sekais.all           #クリックしたタグに紐付けられた投稿を全て表示
  end
  
  def mysekai
      @user = current_user
      @sekais =  current_user.sekais
      @tag_list = Tag.all
  end
  
  def favindex
      @user = current_user
      @sekais = Sekai.find(Favorite.group(:sekai_id).order('count(user_id) desc').limit(100).pluck(:sekai_id))
      @sekais_nil = Sekai.includes(:favorites).where( :favorites => { :id => nil } ).limit(100 - @sekais.length)
      @sekais.push(@sekais_nil)
      @sekais.flatten!      
      @tag_list = Tag.all
  end

  private
  # ストロングパラメータ
  def sekai_params
    params.require(:sekai).permit(:name, :introduction, :image, :tag_id)
  end
  
  def favorite_params
    params.require(:sekai).permit(:name, :introduction, :image, :tag_id)
  end
    
end

app/helpers/sekais_helper.rb
module SekaisHelper
end

app/helpers/user/sekais_helper.rb
module User::SekaisHelper
end

app/views/sekais/_favindex.html.erb
<table class='table table-hover table-inverse'>
  </tbody>
    <% sekais.each.with_index(1) do |sekai, i| %>
    <% if sekai.favorited_by?(current_user) %>
    
      <tr>
        <div>
          <p>
        <td>
          第
          <%= i %>
          位
        </td>
        <span>
              <td class="favorite-btn">
                <%= render "favorites/favorite-btn", sekai: sekai %>
              </td>
            </span>
          </p>
          <td>
        世界の名:
        <%= link_to sekai.name, "/sekais/#{sekai.id}" %>
          </td>
          <td>
        <%= attachment_image_tag sekai, :image, format: 'jpeg', size: "100x100" %>
          </td>
        </div>
      </tr>
  <% else %>
  <% end %>
  <% end %>
</table>

app/views/sekais/_index.html.erb
<table class='table table-hover table-inverse'>
  </tbody>
    <% sekais.each.with_index(1) do |sekai, i| %>
      <tr>
        <div>
          <p>
        <td>
          第
          <%= i %>
          位
        </td>
        <span>
              <td class="favorite-btn">
                <%= render "favorites/favorite-btn", sekai: sekai %>
              </td>
            </span>
          </p>
          <td>
        世界の名:
        <%= link_to sekai.name, "/sekais/#{sekai.id}" %>
          </td>
          <td>
        <%= attachment_image_tag sekai, :image, format: 'jpeg', size: "100x100" %>
          </td>
        </div>
      </tr>
    <% end %>
</table>

app/views/sekais/_tagindex.html.erb
<div id="要素リスト"> </div>
<% tag_list.each do |list| %>
    <% if list.sekais.count == 0 %>
        <% else %>
            <span>
                <%= (link_to list.tag_name, tag_sekais_path(list.id)) %>
                <%= ("(#{list.sekais.count})") %>
            </span>
        <% end %>                                          
    <% end %>

app/views/sekais/_userinfo.html.erb
<table class='table'>
    <div>
        <h2>観測者</h2>
        <tr>
            <th><%= user.name %></th>
        </tr>      
        <tr>
            <th>    <%= link_to "自己との対話", user_path(user.id) %></th>
        </tr>    
    </div>
</table>
<table class='table'>
    <div>
        <%= link_to "創造を開始する", "/sekais/new" %>
</table>

app/views/sekais/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <h1>改変</h1>
    <!-- form_with部分 -->
    <%= form_with model: @sekai, url:sekai_path(@sekai.id), local:true do |f| %>
    <h4>画像</h4>
    <%= f.attachment_field :image %>
    <h4>世界の名</h4>
    <%= f.text_field :name %>
    <h4>概要</h4>
    <%= f.text_area :introduction, size: "100x10" %>
    
    <br>
    <%= "半角スペースを入力することで複数の要素を付けることができます。" %>
    <%= "例：SF スチームパンク ナーロッパ  地動説" %>
    <%= f.text_field :tag_name, value: @tags %>
    <br>
    <div>
      <tr>
        <th>    <%= "今この世界が持っている要素" %></th>
        <%= render 'tagindex', tag_list: @tag_list%>
      </tr>    
    </div>
    <%= f.submit '改変' %>
    
    <%= link_to "崩壊", sekai_path(@sekai.id), method: :delete, "data-confirm" => "世界が軋む……。崩壊させますか？" %>
    <% end %>
  </div>
</div>

app/views/sekais/favindex.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class="col-md-3 offset-md-1 px-5 px-sm-0 mx-auto">
    
    <%= render 'userinfo', user: @user%>

    <%= render 'tagindex', tag_list: @tag_list%>
    </div>
    
    <div class='col-md-8 offset-md-1'>
    
    
    <h1>お気に入りの世界一覧</h1>
      <%= render 'favindex', sekais: @sekais%>
    
    </div>
  </div>
</div>

app/views/sekais/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class="col-md-3 offset-md-1 px-5 px-sm-0 mx-auto">
    
    <%= render 'userinfo', user: @user%>
    
    <%= render 'tagindex', tag_list: @tag_list%>
    </div>
    
    <div class='col-md-8 offset-md-1'>
    <h1>世界一覧</h1>
    <%= render 'index', sekais: @sekais%>
    </div>
  </div>
</div>

app/views/sekais/mysekai.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class="col-md-3 offset-md-1 px-5 px-sm-0 mx-auto">
    
    <%= render 'userinfo', user: @user%>

    <%= render 'tagindex', tag_list: @tag_list%>
    </div>
    
    <div class='col-md-8 offset-md-1'>
    
    
    <h1>自分の世界一覧</h1>
      <%= render 'index', sekais: @sekais%>
    
    </div>
  </div>
</div>

app/views/sekais/new.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
      <div class="col-md-11 offset-md-1 px-5 px-sm-0 mx-auto">
      <div>
      <% if @sekai.errors.any? %>
        <%= @sekai.errors.count %>件のエラーが発生しました
        <% @sekai.errors.full_messages.each do |message| %>
          <%= message %>
   　　   <% end %>
      <% end %>
      <h1>新規投稿</h1>
      </div>    <!-- form_with部分 -->
      <%= form_with model: @sekai, url:'/sekais', local:true do |f| %>
        <h4>画像</h4>
        <%= f.attachment_field :image %>
        <h4>世界の名</h4>
        <%= f.text_field :name %>
        <h4>概要</h4>
        <%= f.text_area :introduction, size: "100x10" %>
        
        <br>
        <%= "半角スペースを入力することで複数の要素を付けることができます。" %>
        </br>
        <br>
        <%= "例：SF スチームパンク ナーロッパ　地動説" %>
        <%= f.text_field :tag_name %>
        </br>
        <%= f.submit '創造' %>
      <% end %>
    </div>
  </div>
</div>

app/views/sekais/search.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class="col-md-3 offset-md-1 px-5 px-sm-0 mx-auto">
        
    <div id="要素リスト"> </div>
    <% @tag_list.each do |list| %>
    <% if list.sekais.count == 0 %>
    <% else %>
  
    <span>
       <%= (link_to list.tag_name, tag_sekais_path(list.id)) %>
       <%= ("(#{list.sekais.count})") %>
    </span>
    <% end %>                                          
    <% end %>                          
    </div>
    
    <div class='col-md-8 offset-md-1'>

    <h2> 投稿一覧 </h2>
        <div id="要素によって絞り込んだ世界一覧">
        </div>
        <%= "要素が ─ " %>
        <%= "#{@tag.tag_name}" %>
        <%= " ─ の世界一覧" %>
        <br /> 
        <% @sekais.each do |post| %>
        <%= (link_to post.name, post) %>
        <% end %>
        <br /> 
        <%= (link_to '俯瞰する', sekais_path) %>
    </div>
  </div>
</div>

app/views/sekais/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class="col-md-11 offset-md-1 px-5 px-sm-0 mx-auto">
    <h4>世界の名</h4>
    <p><%= @sekai.name %></p>
    
    <h4>創造主</h4>
    <p><%= @sekai.user.name %></p><h4>タグ</h4>
    
    <% @sekai_tags.each do |list| %>
      <span>
       <%= link_to list.tag_name, tag_sekais_path(list.id) %>
        </span>
      <% end %>
    
    
    <h4>画像</h4>
    <%= attachment_image_tag @sekai, :image, format: 'jpeg', size: "600x600" %>
    <h4>概要</h4>
    <p><%= @sekai.introduction %></p>
    
    <h4>コメント</h4>
    <table class="sekai_comments">
      <%= render 'comments/index', sekai: @sekai %>
    </table>
    <%= form_with(model:[@sekai,@comment], local: true) do |f| %>
      <%= f.text_area :comment, size:"90x5" %>
      <%= f.submit '送信'%>
    <% end %>
    
        <% if current_user.admin? %>
　　　　<%= link_to "編集", edit_sekai_path(@sekai.id) %>        
　　　　
        <% elsif current_user.admin == true %>
　　　　<%= link_to "編集", edit_sekai_path(@sekai.id) %>        
        
        <% elsif current_user == @sekai.user %>
　　　　<%= link_to "編集", edit_sekai_path(@sekai.id) %>        
        <% end %>
    </div>
  </div>
</div>