config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'
  get 'comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
devise_for :users, controllers: 
      {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

devise_for :admins, controllers: 
      {
        sessions: 'admins/sessions'
      }
      
      
  root 'homes#top'
    get 'top' => 'homes#top'
    get 'sekais/mysekai' => 'sekais#mysekai'
    get '/sekais/myfav' => 'sekais#favindex'
    post 'sekais' => 'sekais#create'
    patch 'sekais/:id' => 'sekais#update'
  
  resources :sekais do
     resource :favorites, only: [:create, :destroy]
     resources :comments, only: [:create, :destroy]
     resources :tags

  end
  
  resources :users  
    get 'favorite_rank' => 'sekais#favorite_rank'
    
    
  resources :tags do
    get 'sekais', to: 'sekais#search'
  end
  
    get '/search', to: 'search#search'

  
#   resources :users do
#         resources :sekais

#   end#   resources :sekais
  
#  get 'user/sekais/new', to: 'user/sekais#new'

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
	belongs_to :sekai
	validates_uniqueness_of :sekai_id, scope: :user_id    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
      before_action :authenticate_user!

  def create
    @sekai = Sekai.find(params[:sekai_id])
    favorite = @sekai.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @sekai = Sekai.find(params[:sekai_id])
    favorite = @sekai.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if sekai.favorited_by?(current_user) %>
  <%= link_to sekai.favorites.count, sekai_favorites_path(sekai), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to sekai.favorites.count, sekai_favorites_path(sekai), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>

app/views/favorites/create.html.erb
$("#sekai_<%= @sekai.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', sekai: @sekai) %>");

app/views/favorites/destroy.html.erb
$("#sekai_<%= @sekai.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', sekai: @sekai) %>");