config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'
  get 'comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
devise_for :users, controllers: 
      {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

devise_for :admins, controllers: 
      {
        sessions: 'admins/sessions'
      }
      
      
  root 'homes#top'
    get 'top' => 'homes#top'
    get 'sekais/mysekai' => 'sekais#mysekai'
    get '/sekais/myfav' => 'sekais#favindex'
    post 'sekais' => 'sekais#create'
    patch 'sekais/:id' => 'sekais#update'
  
  resources :sekais do
     resource :favorites, only: [:create, :destroy]
     resources :comments, only: [:create, :destroy]
     resources :tags

  end
  
  resources :users  
    get 'favorite_rank' => 'sekais#favorite_rank'
    
    
  resources :tags do
    get 'sekais', to: 'sekais#search'
  end
  
    get '/search', to: 'search#search'

  
#   resources :users do
#         resources :sekais

#   end#   resources :sekais
  
#  get 'user/sekais/new', to: 'user/sekais#new'

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
	belongs_to :sekai

	validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    	before_action :authenticate_user!

	def create
		@sekai = Sekai.find(params[:sekai_id])
		@sekai_comment = Comment.new(sekai_comment_params)
		@sekai_comment.sekai_id = @sekai.id
		@sekai_comment.user_id = current_user.id
		if @sekai_comment.save
           redirect_to sekai_path(@sekai.id)
        else
        render 'error'
        end
	end

	def destroy
		@sekai = Sekai.find(params[:sekai_id])
  	sekai_comment = @sekai.comments.find(params[:id])
		sekai_comment.destroy
	end

	private
	def sekai_comment_params
		params.require(:comment).permit(:comment)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<% sekai.comments.each do |comment| %>
  <% comment_user = comment.user %>
  <tr>
  	<td>
  		<%#= link_to user_path(comment_user), class: "user_#{comment_user.id}" do %>
    		<%= comment_user.name %>
  		<%# end %>
  	</td>
  	<td><%= comment.comment %></td>
  	<% if current_user == comment_user %>
    	<td>
    	  <%#= link_to 'Destroy', comment_path(comment.sekai_id, comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %>
<%= link_to "削除", sekai_comment_path(comment.sekai_id, comment.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>    	</td>
  	<% end %>
  </tr>
<% end %>

app/views/comments/create.html.erb
$("#sekai_<%= @sekai.id %> .comments-count").html("コメント数: <%= @sekai.sekai_comments.count %>");
$(".sekai_comments").html("<%= j(render 'sekai_comments/index', sekai: @sekai) %>");
$("#sekai_comment_comment").val("");

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/error.js.erb
$(".body > .container").prepend("<%= j(render 'layouts/errors', obj: @sekai_comment) %>");