config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'
  get 'comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
devise_for :users, controllers: 
      {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

devise_for :admins, controllers: 
      {
        sessions: 'admins/sessions'
      }
      
      
  root 'homes#top'
    get 'top' => 'homes#top'
    get 'sekais/mysekai' => 'sekais#mysekai'
    get '/sekais/myfav' => 'sekais#favindex'
    post 'sekais' => 'sekais#create'
    patch 'sekais/:id' => 'sekais#update'
  
  resources :sekais do
     resource :favorites, only: [:create, :destroy]
     resources :comments, only: [:create, :destroy]
     resources :tags

  end
  
  resources :users  
    get 'favorite_rank' => 'sekais#favorite_rank'
    
    
  resources :tags do
    get 'sekais', to: 'sekais#search'
  end
  
    get '/search', to: 'search#search'

  
#   resources :users do
#         resources :sekais

#   end#   resources :sekais
  
#  get 'user/sekais/new', to: 'user/sekais#new'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
	belongs_to :sekai

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
	belongs_to :sekai
	validates_uniqueness_of :sekai_id, scope: :user_id    
end

app/models/sekai.rb
class Sekai < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  
  attachment :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end      
	
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
  
    old_tags.each do |old|
      self.tag_maps.delete Tag.find_by(tag_name: old)
    end
  
    new_tags.each do |new|
      new_tag_map = Tag.find_or_create_by(tag_name: new)
      self.tag_maps << new_tag_map
    end
  end
  
  
  def self.search_for(content)
    Sekai.where('name LIKE ?', '%'+content+'%')
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :sekais, through: :tag_maps
  
  def self.search_for(content)
    Tag.where('tag_name LIKE ?', '%'+content+'%')
  end  
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :sekai
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :sekais, dependent: :destroy
  
  def self.search_for(content, method)
    Sekai.where('name LIKE ?', '%'+content+'%')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    	before_action :authenticate_user!

	def create
		@sekai = Sekai.find(params[:sekai_id])
		@sekai_comment = Comment.new(sekai_comment_params)
		@sekai_comment.sekai_id = @sekai.id
		@sekai_comment.user_id = current_user.id
		if @sekai_comment.save
           redirect_to sekai_path(@sekai.id)
        else
        render 'error'
        end
	end

	def destroy
		@sekai = Sekai.find(params[:sekai_id])
  	sekai_comment = @sekai.comments.find(params[:id])
		sekai_comment.destroy
	end

	private
	def sekai_comment_params
		params.require(:comment).permit(:comment)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
  
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    
	before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		if @model == 'sekai'
			@records = Sekai.search_for(@content)
		elsif  @model == 'tag'
			@records = Tag.search_for(@content)
		end
	end
end

app/controllers/sekais_controller.rb
class SekaisController < ApplicationController
    
    def new
    @sekai = current_user.sekais.new #(favorite_params)
    end
    
  def create
    # # １. データを新規登録するためのインスタンス作成
    # sekai = Sekai.new(sekai_params)
    # # ２. データをデータベースに保存するためのsaveメソッド実行
    # sekai.save
    # # ３. トップ画面へリダイレクト
    # redirect_to '/sekais'
    
    @sekai = current_user.sekais.new(sekai_params)
    tag_list = params[:sekai][:tag_name].split(' ')
    if @sekai.save
      tags = []
      tag_list.each do |tag_name|
        tags << Tag.find_or_create_by(tag_name: tag_name)
      end
      @sekai.tags = tags
      # @sekai.save_tag(tag_list)
    redirect_to '/sekais'
    else
    render :new
    end
  end
  
  def index
      @user = current_user
      @sekais =  current_user.sekais
      @sekais = Sekai.find(Favorite.group(:sekai_id).order('count(user_id) desc').limit(100).pluck(:sekai_id))
      if @sekais.length < 100
      @sekais_nil = Sekai.includes(:favorites).where( :favorites => { :id => nil } ).limit(100 - @sekais.length)
      else
      @sekais_nil = []
      end
      @sekais.push(@sekais_nil)
      @sekais.flatten!
      #上のコードを実装したい。したのは仮
      #@sekais = Sekai.all
     # sekais = Sekai.includes(:favorites).references(:favorites).group('sekai_id').order('user_id desc').each {|s| puts s.name}
      @tag_list = Tag.all
      # @sekai = current_user.sekais.new
      
  end
  
  def show
      @user = current_user
    @sekai = Sekai.find(params[:id])
    @sekai_tags = @sekai.tags  
    @comment = Comment.new

  end
  
  def edit
    @sekai = Sekai.find(params[:id])
    @tag_list = @sekai.tags  

  end
  
  def update
    @sekai = Sekai.find(params[:id])
    tag_list = params[:sekai][:tag_name].split(' ')
    if @sekai.update(sekai_params)
      tags = []
      tag_list.each do |tag_name|
        tags << Tag.find_or_create_by(tag_name: tag_name)
      end    
      @sekai.tags = tags
    end
    redirect_to sekais_path(@sekai.id)
  end
  
  def destroy
    sekai = Sekai.find(params[:id])  
    sekai.destroy  
    redirect_to sekais_path  
  end
  
  # def favorite_rank
  #   @sekai = current_user.sekais.new(favorite_params)
  #   tag_list = params[:sekai][:tag_name].split(nil)  
  #   if @sekai.save                                         
  #     @sekai.save_tag(tag_list)                         
  #   redirect_to '/sekais'
  #   else
  #   redirect_to '/sekais'
  #   end
  # end
  
  def search
      @user = current_user
    @tag_list = Tag.all  #こっちの投稿一覧表示ページでも全てのタグを表示するために、タグを全取得
    @tag = Tag.find(params[:tag_id])  #クリックしたタグを取得
    @sekais = @tag.sekais.all           #クリックしたタグに紐付けられた投稿を全て表示
  end
  
  def mysekai
      @user = current_user
      @sekais =  current_user.sekais
      @tag_list = Tag.all
  end
  
  def favindex
      @user = current_user
      @sekais = Sekai.find(Favorite.group(:sekai_id).order('count(user_id) desc').limit(100).pluck(:sekai_id))
      @sekais_nil = Sekai.includes(:favorites).where( :favorites => { :id => nil } ).limit(100 - @sekais.length)
      @sekais.push(@sekais_nil)
      @sekais.flatten!      
      @tag_list = Tag.all
  end

  private
  # ストロングパラメータ
  def sekai_params
    params.require(:sekai).permit(:name, :introduction, :image, :tag_id)
  end
  
  def favorite_params
    params.require(:sekai).permit(:name, :introduction, :image, :tag_id)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @sekais = @user.sekais
    @sekai = Sekai.new
    @tag_list = Tag.all
    
      @sekais_fav = Sekai.find(Favorite.group(:sekai_id).order('count(user_id) desc').limit(100).pluck(:sekai_id))
      @sekais_nil = Sekai.includes(:favorites).where( :favorites => { :id => nil } ).limit(100 - @sekais_fav.length)
      @sekais_fav.push(@sekais_nil)
      @sekais_fav.flatten!      
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sekais_helper.rb
module SekaisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<header>
  <nav>
    <div class='container px-5 px-sm-0'>
      <div class='row'>
        <div class="col-md-3 offset-md-1 px-5 px-sm-0 mx-auto">    
        <div class="container">
          <a>
              <span>お問い合わせ: 3bu1hho@gmail.com</span>
          </a>
        </div>
        </div>
      </div>
    </div>    
  </nav>
</header>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#a5603d;">
    <div class="container">
      <a class="navbar-brand" href="/"><span>世界館</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', sekais_mysekai_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' Sekais',sekais_path ,class: 'fas fa-compass nav-link text-light'%></li>
          <li><%= link_to ' Favorite',sekais_myfav_path ,class: 'fas fa-heart nav-link text-light'%></li>
          <li><%= link_to ' MySekais',sekais_mysekai_path ,class: 'fas fa-paint-brush nav-link text-light'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "世界" => "sekai", "タグ" => "tag" }) %>
    <%#= f.select :model, options_for_select({ "User" => "user", "世界" => "sekai" }) %>
    <%#= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>世界館</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--<%# if user_signed_in? %>-->
    <!--  <li>-->
    <!--    <%#= link_to "ログアウト", destroy_user_session_path, method: :delete %>-->
    <!--  </li>-->
    <!--<%# else %>-->
    <!--  <li>-->
    <!--    <%#= link_to "新規登録", new_user_registration_path %>-->
    <!--  </li>-->
    <!--  <li>-->
    <!--    <%#= link_to "ログイン", new_user_session_path %>-->
    <!--  </li>-->
    <!--<%# end %>-->
    
          <main>
    <%= render 'layouts/header' %>
        <% if user_signed_in? %>
          <%= render 'layouts/search' %>
        <% end %>
      </main>
            <p id="notice"><%= notice %></p>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>